# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hyungook OH
title: Frontend developer
email: nenonenoberneno@gmail.com
website: https://hyungook.github.io/hyungooks-story/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: hyungook
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: hyungookoh
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요,
  신입 프론트엔드 개발자 오형욱입니다.
  지금까지 습득해온 개발/디자인 등의 다양한 능력을 저만의 이야기로 멈추지 않고,
  프로젝트를 통해 대중과 소통하고 교류할 수 있는 <mark>프론트 개발자</mark>가 되고 싶습니다.

  저의 CLIFTON STRENGTHSFINDER 강점 조사 상위 5가지는 '책임/성취/공정성/긍정/절친'입니다.
  목적한 성취를 이루며 공정성 있는 자세로 동료들과 협력하며 동료/선배님들을 실망시키지 않는 책임감 있는 모습 보여드리고 싶습니다.
content:
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        name: Front-end
        description: | # this will include new lines to allow paragraphs
          * Javascript
          * HTML5
          * CSS3
      - layout: left
        name: Library
        description: | # this will include new lines to allow paragraphs
          * React JS
          * React Native
          * Typescript
          * Jquery
      - layout: left
        name: Back-end
        description: | # this will include new lines to allow paragraphs
          * Node JS
      - layout: left
        name: Design
        description: | # this will include new lines to allow paragraphs
          * Photoshop
          * Adobe XD
          * Illustrator

  - title: Growth # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Growth Process
        # link_text: Project Website
        additional_links:
          - title: Growth Process
            icon: fab fa-github
            url: https://github.com/hyungook
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          끊임없는 성장을 꿈꿉니다.
        description: | # this will include new lines to allow paragraphs
          코리아 it 아카데미 학원에서 프론트엔드 6개월 과정과 SBS 아카데미 반응형 웹 6개월 수업을 수료하였고, 학원 외에도 부족한 부분을 보완하기 위해 인프런, 드림코딩 등의 온라인 강의를 통해 꾸준히 학습하고 있습니다.
          그리고, 온라인/오프라인 스터디를 진행하며 스터디원들과 개발 지식/노하우/개발 트렌드 등을 나누며 간단한 토이 프로젝트나 클론 코딩을 진행하며 개발자로서의 능력을 키워가고 있습니다.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Eland Group
        caption: 2018 - 2020
        sub_title: Contents Design
        quote: >
          Deliver the joy of seeing through a sensuous design.
        description: | # this will include new lines to allow paragraphs
          이랜드그룹 인하우스 팀 내에서 이랜드 그룹의 전반적인 콘텐츠 디자인(그래픽, 편집, 로고 등) 업무를 하였습니다.
          사내 홈페이지, 그룹 공식 블로그, 공식 SNS 콘텐츠 디자인과 공식 유튜브 로고 및 기타 그래픽을 제작했습니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
